# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './design.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        MainWindow.setWindowOpacity(0.9)
        MainWindow.setStyleSheet("background: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(46, 0, 140, 255), stop:1 rgba(46, 0, 139, 255));\n"
"")
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(10, 10, 371, 71))
        self.Title.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 20pt \"Bahnschrift Light\";\n"
"border-bottom: 2px solid white;\n"
"padding: 5px;")
        self.Title.setObjectName("Title")
        self.Changelog = QtWidgets.QLabel(self.centralwidget)
        self.Changelog.setGeometry(QtCore.QRect(380, 80, 311, 151))
        self.Changelog.setStyleSheet("font: 25 8pt \"Bahnschrift Light\";\n"
"color: rgb(255, 255, 255);\n"
"border-right: 2px solid white;\n"
"border-bottom: 2px solid white;\n"
"border-left: 2px solid white;\n"
"padding: 5px;")
        self.Changelog.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Changelog.setObjectName("Changelog")
        self.CLTitle = QtWidgets.QLabel(self.centralwidget)
        self.CLTitle.setGeometry(QtCore.QRect(380, 10, 311, 71))
        self.CLTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 20pt \"Bahnschrift Light\";\n"
"border-bottom: 2px solid white;\n"
"padding: 5px;")
        self.CLTitle.setObjectName("CLTitle")
        self.Settings = QtWidgets.QPushButton(self.centralwidget)
        self.Settings.setGeometry(QtCore.QRect(620, 420, 61, 61))
        self.Settings.setStyleSheet("border: none;\n"
"background-color: white;\n"
"border-radius: 15px;\n"
"font: 25 10pt \"Bahnschrift Light\";")
        self.Settings.setObjectName("Settings")
        self.Launch = QtWidgets.QPushButton(self.centralwidget)
        self.Launch.setGeometry(QtCore.QRect(30, 430, 121, 51))
        self.Launch.setStyleSheet("background-color: rgb(162, 255, 162);\n"
"font: 25 10pt \"Bahnschrift Light\";\n"
"border-radius: 15px;")
        self.Launch.setObjectName("Launch")
        self.VList = QtWidgets.QComboBox(self.centralwidget)
        self.VList.setGeometry(QtCore.QRect(170, 460, 101, 22))
        self.VList.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 25 10pt \"Bahnschrift Light\";\n"
"border-radius: 15px;")
        self.VList.setCurrentText("")
        self.VList.setObjectName("VList")
        self.VTitle = QtWidgets.QLabel(self.centralwidget)
        self.VTitle.setGeometry(QtCore.QRect(170, 430, 101, 31))
        self.VTitle.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 25 12pt \"Bahnschrift Light\";\n"
"border-bottom: 2px solid white;\n"
"padding: 5px;")
        self.VTitle.setObjectName("VTitle")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Iris Launcher"))
        self.Title.setText(_translate("MainWindow", "Iris Launcher"))
        self.Changelog.setText(_translate("MainWindow", "<html><head/><body><p>insert changelog here</p></body></html>"))
        self.CLTitle.setText(_translate("MainWindow", "Changelog"))
        self.Settings.setText(_translate("MainWindow", "Settings"))
        self.Launch.setText(_translate("MainWindow", "Launch!"))
        self.VTitle.setText(_translate("MainWindow", "Version"))
